databases:
  - name: rails-users-render  # Use the name of your Render PostgreSQL database
    plan: free

services:
  - type: web
    name: rails-users-render  # Name for your web app
    runtime: ruby
    plan: free
    region: oregon  # Match this to your database's region
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-users-render
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false  # Ensure this key is added manually in the dashboard
      - key: WEB_CONCURRENCY
        value: "2"  # Default for Puma; adjust as needed
