default: &default
  adapter: async
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_development

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_production
  # This is where ActionCable database configuration is usually found
  # If you don't use ActionCable with its own database, you can leave it empty
  cable:
    development:
      <<: *default
    production:
      <<: *default
