default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>

production:
  primary:
    <<: *default
    database: <%= ENV["DB_NAME"] %>

  queue:
    <<: *default
    database: <%= ENV["QUEUE_DB_NAME"] || ENV["DB_NAME"] %>

  cable:
    <<: *default
    database: <%= ENV["CABLE_DB_NAME"] || ENV["DB_NAME"] %>
